language: python
dist: bionic

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=lint
    - python: 2.7
      env: TOXENV=cover
install:
  - pip install tox
script:
  - tox
